version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      # Explicit for clarity; app has same default
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tcgscan
      SECRET_KEY: dev-super-secret
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcgscan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
