[project]
name = "tcgscan"
version = "0.1.0"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy>=2.0",
  "alembic",
  "psycopg2-binary",
  "httpx",
  "python-multipart",
  "opencv-python",
  "faiss-cpu",
  "pytesseract",
  "apscheduler",
]
